spring:
  session:
    store-type: JDBC
    jdbc:
      table-name: session
      cleanup-cron: 0 30 * * * *
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://rm-8vb0q5u3t79l9t6bzoo.mysql.zhangbei.rds.aliyuncs.com:3306/fpl?&autoReconnect=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: tong
    password: Tonglam14
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 180000
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8014
  address: 127.0.0.1