spring:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 8014
  address: 127.0.0.1
